//! Event types forming the contract between the agent loop and the TUI.
//!
//! The agent loop sends [`AgentEvent`]s through an `mpsc` channel to the TUI,
//! which accumulates them into renderable state via [`super::app_state::AppState`].
//! The TUI sends [`ControlSignal`]s back to the agent loop for pause/resume/quit.

use std::fmt;

/// Events emitted by the agent loop, sent via mpsc channel to the TUI.
///
/// Each variant carries enough data for the TUI to render a meaningful log entry
/// and update status indicators. Timestamps are ISO 8601 strings provided by the
/// agent loop (not generated by the TUI) to reflect actual event time.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum AgentEvent {
    /// Agent produced thinking/reasoning text.
    ThoughtText {
        timestamp: String,
        turn: u64,
        content: String,
    },

    /// Agent requested a tool call (execution starting).
    ToolCallStarted {
        timestamp: String,
        turn: u64,
        call_id: String,
        fn_name: String,
        args_summary: String,
    },

    /// Tool call completed with result.
    ToolCallCompleted {
        timestamp: String,
        turn: u64,
        call_id: String,
        fn_name: String,
        result_summary: String,
        full_result: String,
    },

    /// Agent transitioned to a new state.
    StateChanged(AgentState),

    /// Context window pressure updated after a model response.
    ContextPressure {
        usage_pct: f64,
        prompt_tokens: usize,
        context_limit: usize,
    },

    /// Session restarted due to context exhaustion.
    SessionRestarted {
        session_number: u32,
    },

    /// Error occurred during agent execution.
    Error {
        timestamp: String,
        turn: u64,
        message: String,
    },

    /// Agent flagged something noteworthy for the discoveries list.
    Discovery {
        timestamp: String,
        title: String,
        description: String,
    },

    /// Turn and tool-call counters updated (emitted each turn).
    CountersUpdated {
        turn: u64,
        tool_calls: u64,
    },

    /// A sub-agent's lifecycle status changed.
    ///
    /// Emitted by the [`crate::orchestration::manager::SubAgentManager`] when
    /// an agent transitions state (spawned, completed, failed, killed).
    /// The TUI integration plan will wire this into the sub-agent tree panel.
    SubAgentStatusChanged {
        agent_id: String,
        status: String,
        kind: String,
    },
}

/// The five visible agent states shown in the status bar.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub enum AgentState {
    /// Model is generating a response (streaming tokens).
    Thinking,
    /// A tool call is being executed.
    Executing,
    /// Waiting between turns or for input.
    #[default]
    Idle,
    /// User has paused the agent loop.
    Paused,
    /// Agent is sleeping (self-initiated pause via sleep tool).
    Sleeping,
}

impl fmt::Display for AgentState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AgentState::Thinking => write!(f, "Thinking"),
            AgentState::Executing => write!(f, "Executing"),
            AgentState::Idle => write!(f, "Idle"),
            AgentState::Paused => write!(f, "Paused"),
            AgentState::Sleeping => write!(f, "Sleeping"),
        }
    }
}

/// Control signals sent from the TUI to the agent loop.
///
/// Sent via a separate mpsc channel so the agent can check for control
/// messages between turns.
#[derive(Debug, Clone, Copy)]
pub enum ControlSignal {
    /// Pause the agent loop after the current tool call finishes.
    Pause,
    /// Resume a paused agent loop.
    Resume,
    /// Gracefully shut down the agent.
    Quit,
}
